default_language_version: 
    python: python3
default_stages: [commit]
repos:
    -   repo: local
        hooks:
            -   id: isort
                name: isort (python)
                entry: isort
                language: python
                types: [python]

            -   id: black
                name: black
                args: [--line-length=79]
                entry: black
                language: python
                types: [python]

            -   id: flake8
                name: flake8
                entry: flake8
                language: python
                types: [python]

            -   id: mypy
                name: mypy
                exclude: ''
                entry: mypy
                language: python
                types: [python] 


            -   id: pytest
                name: pytest
                entry: pytest tests
                language: python
                types: [python]
                pass_filenames: false
                always_run: false